---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: wikimedia-pagecounter
  namespace: flink-kubernetes-operator
spec:
  image: ghcr.io/ssup2-playground/k8s-data-platform_flink-jobs:commit-98cdfdeb
  flinkVersion: v1_18
  serviceAccount: flink
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    kubernetes.rest-service.exposed.type: LoadBalancer
  jobManager:
    resource:
      cpu: 1
      memory: "1024m"
  taskManager:
    resource:
      cpu: 1
      memory: "1024m"
    replicas: 2
  job:
    jarURI: local:///opt/flink/usrlib/mediawiki-page-create-counter.jar
    entryClass: ssup2.flink.MediaWikiPageCreateCounterJob
    parallelism: 2
    upgradeMode: stateless
    state: running
  podTemplate:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9249"